### ISSUE TITLE
Evaluation results of PanoFCN

### ISSUE THREAD

**Issue by Yinyf0804** [qqlu/Entity#16]
Thanks for your great work. I have a question that how the panoptic results of PanoFCN or DETR transfered to the entity segmentation results?

**Comment by qqlu** [comment]
We have updated the results of PanopticFCN and DETR in our arxiv v2 paper.

**Comment by Yinyf0804** [comment]
Thanks for your reply. Yes I have noticed that in the paper, but how the panoptic results of PanoFCN or DETR transfered to the entity segmentation results?  Do all the segments in the panoptic results including thing and stuff be regarded as 'instances' directly before evaluation or any postprocess are used?

**Comment by qqlu** [comment]
We regard all entities as instances in PanopticFCN and DETR without the modification of the code.
