### ISSUE TITLE
CA-SSL: Class-Agnostic Semi-Supervised Learning for Detection and Segmentation (ECCV2022) 

### ISSUE THREAD

**Issue by leichaoyang** [qqlu/Entity#31]
Where can I find the code of the CA-SSL?

**Comment by qqlu** [comment]
Hello,

You can directly use the existing entity segmentation model to generate entity masks. For example, directly use the CropFormer Visualization code. https://github.com/qqlu/Entity/blob/main/Entityv2/CODE.md.

This could be directly used for pseudo labels.

We will release the pseudo labels on 1,700,000 open images soon.

**Comment by leichaoyang** [comment]
Can you send me the code of CA-SSL? I want to learn the framework of the CA-SSL.

**Comment by qqlu** [comment]
Sorry, I do not understand your requirements.

The CA-SSL mainly uses the unlabeled data and its class-agnostic pesudo labels to warm-up the network whatever the framework be used.

**Comment by leichaoyang** [comment]
Thank you, I understand the idea of the paper.
