### ISSUE TITLE
Missing config files

### ISSUE THREAD

**Issue by 594zyc** [qqlu/Entity#32]
Hi,

Thanks for releasing such a great dataset! I am trying to replicate the result using the released weights on Huggingface, but found that some config files are missing, such as [this one](https://huggingface.co/datasets/qqlu1992/Adobe_EntitySeg/tree/main/CropFormer_model/Entity_Segmentation/Mask2Former_swin_large_w7_3x). Could you upload these files? 

Thanks

**Comment by qqlu** [comment]
Hi,

Configs are in Entityv2/CropFormer/configs/entityv2/entity_segmentation.

Thanks.

**Comment by 594zyc** [comment]
Got it. Thanks!
